export const kidsShoes = [
 {
  id: 22,
  title: 'Air Jordan 1 Mid',
  price: '$120.00',
  mainImage: '/KIDSIMGS/Air Jordan 1 Mid-1 (1).png',
  images: [
    '/KIDSIMGS/Air Jordan 1 Mid-1 (2).png',
    '/KIDSIMGS/Air Jordan 1 Mid-1 (3).png',
    '/KIDSIMGS/Air Jordan 1 Mid-1 (4).png',
    '/KIDSIMGS/Air Jordan 1 Mid-1 (5).png',
    '/KIDSIMGS/Air Jordan 1 Mid-1 (6).png',
    '/KIDSIMGS/Air Jordan 1 Mid-1 (7).png',
    '/KIDSIMGS/Air Jordan 1 Mid-1 (8).png',
  ],
  description:'Air Jordan 1 Mid',
  text:'Diese Version des AJ1 ist eine Neuauflage des ersten Signature-Modells von Mike mit einem frischen Farbmix. Hochwertige Materialien, eine weiche Dämpfung und ein gepolsterter Schuhkragen am Knöchel sorgen für optimalen Halt und feiern den Schuh, mit dem alles begann.',
  sizes:['35.5', '36', '36.5', '37.5', '38','38.5', '39','40', '41', '42'],
  stock: 50,
  type: ['girl', 'kids', 'winter'],
 },
 {
  id: 23,
  title: 'Air Jordan 1 Low',
  price: '$180.00',
  mainImage: '/KIDSIMGS/Jordan 1 Mid-1 (2).png',
  images: [
    '/KIDSIMGS/Jordan 1 Mid-1 (1).png',
    '/KIDSIMGS/Jordan 1 Mid-1 (3).png',
    '/KIDSIMGS/Jordan 1 Mid-1 (4).png',
    '/KIDSIMGS/Jordan 1 Mid-1 (5).png',
    '/KIDSIMGS/Jordan 1 Mid-1 (6).png',
    '/KIDSIMGS/Jordan 1 Mid-1 (7).png',
    '/KIDSIMGS/Jordan 1 Mid-1 (8).png',
  ],
  description:'Jordan 1 Mid',
  text:'Diese Version des AJ1 ist eine Neuauflage des ersten Signature-Modells von Mike mit einem frischen Farbmix. Hochwertige Materialien, eine weiche Dämpfung und ein gepolsterter Schuhkragen am Knöchel sorgen für optimalen Halt und feiern den Schuh, mit dem alles begann.',
  sizes:['35.5', '36', '36.5', '37.5', '38','38.5', '39','40', '41', '42'],
  stock: 50,
  type: ['girl', 'kids'],
 },
 {
  id: 24,
  title: 'Air Jordan 1 Low',
  price: '$140.00',
  mainImage: '/KIDSIMGS/Air Jordan 1 Mid-1 (1).png',
  images: [
    '/KIDSIMGS/Air Jordan 1 Mid-1 (2).png',
    '/KIDSIMGS/Air Jordan 1 Mid-1 (3).png',
    '/KIDSIMGS/Air Jordan 1 Mid-1 (4).png',
    '/KIDSIMGS/Air Jordan 1 Mid-1 (5).png',
    '/KIDSIMGS/Air Jordan 1 Mid-1 (6).png',
    '/KIDSIMGS/Air Jordan 1 Mid-1 (7).png',
    '/KIDSIMGS/Air Jordan 1 Mid-1 (8).png',
  ],
  description:'Air Jordan 1 Low',
  text:'Diese Version des AJ1 ist eine Neuauflage des ersten Signature-Modells von Mike mit einem frischen Farbmix. Hochwertige Materialien, eine weiche Dämpfung und ein gepolsterter Schuhkragen am Knöchel sorgen für optimalen Halt und feiern den Schuh, mit dem alles begann.',
  sizes:['35.5', '36', '36.5', '37.5', '38','38.5', '39','40', '41', '42'],
  stock: 50,
  type: ['young', 'kids'],
 },
 {
  id: 25,
  title: 'Air Jordan Legacy',
  price: '$160.00',
  mainImage: '/KIDSIMGS/Air Jordan Legacy-1 (1).png',
  images: [
    '/KIDSIMGS/Air Jordan Legacy-1 (2).png',
    '/KIDSIMGS/Air Jordan Legacy-1 (3).png',
    '/KIDSIMGS/Air Jordan Legacy-1 (4).png',
    '/KIDSIMGS/Air Jordan Legacy-1 (5).png',
    '/KIDSIMGS/Air Jordan Legacy-1 (6).png',
    '/KIDSIMGS/Air Jordan Legacy-1 (7).png',
    '/KIDSIMGS/Air Jordan Legacy-1 (8).png',
    '/KIDSIMGS/Air Jordan Legacy-1 (9).png',
  ],
  description:'Air Jordan Legacy',
  description:'Air Jordan 1 Low',
  text:'Diese Version des AJ1 ist eine Neuauflage des ersten Signature-Modells von Mike mit einem frischen Farbmix. Hochwertige Materialien, eine weiche Dämpfung und ein gepolsterter Schuhkragen am Knöchel sorgen für optimalen Halt und feiern den Schuh, mit dem alles begann.',
  sizes:['35.5', '36', '36.5', '37.5', '38','38.5', '39','40', '41', '42'],
  stock: 50,
  type: ['young', 'kids', 'winter'],
 }
]