export const menShoes = [
 {
  id: 17,
  title: 'Jumpman MVP',
  price: '$118,99',
  mainImage: '/MENIMAGES/JORDAN+MVP-1 (1).png',
  images: [
    '/MENIMAGES/JORDAN+MVP-1 (2).png',
    '/MENIMAGES/JORDAN+MVP-1 (3).png',
    '/MENIMAGES/JORDAN+MVP-1 (4).png',
    '/MENIMAGES/JORDAN+MVP-1 (5).png',
    '/MENIMAGES/JORDAN+MVP-1 (6).png',
    '/MENIMAGES/JORDAN+MVP-1 (7).png',
  ],
  description: 'Jumpman MVP',
  Text: 'Wir haben die Neuauflage nicht erfunden, aber wenn man bedenkt, welches Material wir testen müssen, ist es eine klare Sache. Wir haben Elemente des AJ6, 7 und 8 übernommen und in einem komplett neuen Schuh vereint, der die ersten drei Meisterschaftsrunden von Michael Jordan feiert. Mit Leder-, Textil- und Nubuk-Details sind diese Sneaker eine Hommage an ein Vermächtnis, das dich dazu ermutigt, deinen eigenen Style zu betonen.',
  sizes:['40', '41', '42', '42,5', '43', '44', '44,5', '45', '45,5', '46', '47,5', '48,5'],
  stock: 80,
  type: ['men', 'summer', 'winter']
 },
 {
  id: 14,
  title: 'Jumpman MVP',
  price: '$160.00',
  mainImage: '/MENIMAGES/JORDAN+MVP-2 (1).png',
  images: [
    '/MENIMAGES/JORDAN+MVP-2 (2).png',
    '/MENIMAGES/JORDAN+MVP-2 (3).png',
    '/MENIMAGES/JORDAN+MVP-2 (4).png',
    '/MENIMAGES/JORDAN+MVP-2 (5).png',
    '/MENIMAGES/JORDAN+MVP-2 (6).png',
    '/MENIMAGES/JORDAN+MVP-2 (7).png',
    '/MENIMAGES/JORDAN+MVP-2 (8).png',
  ],
  description: 'Jumpman MVP',
  Text: 'Wir haben die Neuauflage nicht erfunden, aber wenn man bedenkt, welches Material wir testen müssen, ist es eine klare Sache. Wir haben Elemente des AJ6, 7 und 8 übernommen und in einem komplett neuen Schuh vereint, der die ersten drei Meisterschaftsrunden von Michael Jordan feiert. Mit Leder-, Textil- und Nubuk-Details sind diese Sneaker eine Hommage an ein Vermächtnis, das dich dazu ermutigt, deinen eigenen Style zu betonen.',
  sizes:['40', '41', '42', '42,5', '43', '44', '44,5', '45', '45,5', '46', '47,5', '48,5'],
  stock: 80,
  type: ['men', 'summer', 'winter']
 },
 {
  id: 15,
  title: 'Jordan Spizike',
  price: '$180.00',
  mainImage: '/MENIMAGES/Jordan Spizike Low-1 (1).png',
  images: [
    '/MENIMAGES/Jordan Spizike Low-1 (2).png',
    '/MENIMAGES/Jordan Spizike Low-1 (3).png',
    '/MENIMAGES/Jordan Spizike Low-1 (4).png',
    '/MENIMAGES/Jordan Spizike Low-1 (5).png',
    '/MENIMAGES/Jordan Spizike Low-1 (6).png',
    '/MENIMAGES/Jordan Spizike Low-1 (7).png',
    '/MENIMAGES/Jordan Spizike Low-1 (8).png',
  ],
  description: 'Jordan Spizike Low',
  Text: 'Der Spizike kombiniert Elemente von fünf klassischen Jordan-Modellen. Das Ergebnis ist ein außergewöhnlicher Sneaker. Er ist eine Hommage an Spike Lee, der Hollywood und Basketball in einem kulturellen Moment offiziell zusammenführte. Du bekommst also einen stylishen Schuh mit etwas Geschichte.',
  sizes:['40', '41', '42', '42,5', '43', '44', '44,5', '45', '45,5', '46', '47,5', '48,5'],
  stock: 80,
  type: ['men', 'summer']
 },
 {
  id: 16,
  title: 'Jordan Spizike',
  price: '$200.00',
  mainImage: '/MENIMAGES/Jordan Spizike Low-2 (1).png',
  images: [
    '/MENIMAGES/Jordan Spizike Low-2 (2).png',
    '/MENIMAGES/Jordan Spizike Low-2 (3).png',
    '/MENIMAGES/Jordan Spizike Low-2 (4).png',
    '/MENIMAGES/Jordan Spizike Low-2 (5).png',
    '/MENIMAGES/Jordan Spizike Low-2 (6).png',
    '/MENIMAGES/Jordan Spizike Low-2 (7).png',
    '/MENIMAGES/Jordan Spizike Low-2 (8).png',
  ],
  description: 'Jordan Spizike Low',
  Text: 'Der Spizike kombiniert Elemente von fünf klassischen Jordan-Modellen. Das Ergebnis ist ein außergewöhnlicher Sneaker. Er ist eine Hommage an Spike Lee, der Hollywood und Basketball in einem kulturellen Moment offiziell zusammenführte. Du bekommst also einen stylishen Schuh mit etwas Geschichte.',
  sizes:['40', '41', '42', '42,5', '43', '44', '44,5', '45', '45,5', '46', '47,5', '48,5'],
  stock: 80,
  type: ['men', 'winter']
 },
]