export const sportShoes = [
 {
  id: 26,
  title: 'JORDAN 3',
  price: '$1,500.00',
  mainImage: '/SPORTSIMGS/JORDAN 3 -1 (1).png',
  images: [
    '/SPORTSIMGS/JORDAN 3 -1 (2).png',
    '/SPORTSIMGS/JORDAN 3 -1 (3).png',
    '/SPORTSIMGS/JORDAN 3 -1 (4).png',
    '/SPORTSIMGS/JORDAN 3 -1 (5).png',
    '/SPORTSIMGS/JORDAN 3 -1 (6).png',
    '/SPORTSIMGS/JORDAN 3 -1 (7).png',
    '/SPORTSIMGS/JORDAN 3 -1 (8).png',
    '/SPORTSIMGS/JORDAN 3 -1 (9).png',
  ],
  description:'JORDAN 3',
  text:'Zions dritter Signature-Schuh ist eine Hommage an die Hingabe, mit der er sein einzigartiges Spiel entwickelt hat. Er ist vollgepackt mit spielfeldbereiter Technologie und wurde für Basketballspieler:innen entwickelt, die sowohl auf dem Boden als auch in der Luft dominieren. Dank sicherer Bodenhaftung und zuverlässigen Halts sind explosive Sprünge und weiche Landungen kein Problem. Im Zion 3 bleibt dein Fuß schön fixiert, damit du auf deine eigene Weise fliegen kannst.',
  sizes:['35.5', '36', '36.5', '37.5', '38','38.5', '39','40', '41', '42'],
  stock: 50,
  type: ['young', 'kids', 'sport'],
 },
 {
  id: 27,
  title: 'Jordan One Take ',
  price: '$1,800.00',
  mainImage: '/SPORTSIMGS/Jordan One Take -1 (1).png',
  images: [
    '/SPORTSIMGS/Jordan One Take -1 (2).png',
    '/SPORTSIMGS/Jordan One Take -1 (3).png',
    '/SPORTSIMGS/Jordan One Take -1 (4).png',
    '/SPORTSIMGS/Jordan One Take -1 (5).png',
    '/SPORTSIMGS/Jordan One Take -1 (6).png',
    '/SPORTSIMGS/Jordan One Take -1 (7).png',
    '/SPORTSIMGS/Jordan One Take -1 (8).png',
  ],
  description: 'Jordan One Take ',
  Text: 'Der Spizike kombiniert Elemente von fünf klassischen Jordan-Modellen. Das Ergebnis ist ein außergewöhnlicher Sneaker. Er ist eine Hommage an Spike Lee, der Hollywood und Basketball in einem kulturellen Moment offiziell zusammenführte. Du bekommst also einen stylishen Schuh mit etwas Geschichte.',
  sizes:['40', '41', '42', '42,5', '43', '44', '44,5', '45', '45,5', '46', '47,5', '48,5'],
  stock: 80,
  type: ['men', 'sport']
 },
 {
  id: 28,
  title: 'Air Jordan Heiress',
  price: '$1,200.00',
  mainImage: '/SPORTSIMGS/Air Jordan Heiress-1 (1).png',
  images: [
    '/SPORTSIMGS/Air Jordan Heiress-1 (2).png',
    '/SPORTSIMGS/Air Jordan Heiress-1 (3).png',
    '/SPORTSIMGS/Air Jordan Heiress-1 (4).png',
    '/SPORTSIMGS/Air Jordan Heiress-1 (5).png',
    '/SPORTSIMGS/Air Jordan Heiress-1 (6).png',
    '/SPORTSIMGS/Air Jordan Heiress-1 (7).png',
    '/SPORTSIMGS/Air Jordan Heiress-1 (8).png',
    '/SPORTSIMGS/Air Jordan Heiress-1 (9).png',
  ],
  description: 'Air Jordan Heiress',
  text: 'Die Air Jordan Heiress ist ein modernes und elegantes Sneaker, das dank des geschmückten Materials und der hohen Qualität von Jordan gebaut ist. Sie ist vollgepackt mit einer Sport-Ferse und einer schwarzen Stiefelschaltung, die zu einer schnellen und leichten Fahrt führen kann.',
  sizes:['40', '41', '42', '42,5', '43', '44', '44,5', '45', '45,5', '46', '47,5', '48,5'],
  stock: 60,
  type: ['women', 'sport']
 },
 {
  id: 29,
  title: 'Jordan Stay Loyal',
  price: '$1,400.00',
  mainImage: '/SPORTSIMGS/Jordan Stay Loyal 3-1 (1).png',
  images: [
    '/SPORTSIMGS/Jordan Stay Loyal 3-1 (2).png',
    '/SPORTSIMGS/Jordan Stay Loyal 3-1 (3).png',
    '/SPORTSIMGS/Jordan Stay Loyal 3-1 (4).png',
    '/SPORTSIMGS/Jordan Stay Loyal 3-1 (5).png',
    '/SPORTSIMGS/Jordan Stay Loyal 3-1 (6).png',
    '/SPORTSIMGS/Jordan Stay Loyal 3-1 (7).png',
    '/SPORTSIMGS/Jordan Stay Loyal 3-1 (8).png',
  ],
  description: 'Jordan Stay Loyal',
  text: 'Die Jordan Stay Loyal ist ein Sneaker, das dank der geschmückten Materials und der hohen Qualität von Jordan gebaut ist. Sie ist vollgepackt mit einer Sport-Ferse und einer schwarzen Stiefelschaltung, die zu einer schnellen und leichten Fahrt führen kann.',
  sizes:['40', '41', '42', '42,5', '43', '44', '44,5', '45', '45,5', '46', '47,5', '48,5'],
  stock: 70,
  type: ['girl', 'sport']
 }
]