export const womenShoes = [
 {
  id: 18,
  title: 'Air Jordan 1 Low',
  price: '$150.00',
  mainImage: '/WOMENSIMGS/Air Jordan 1 Low-1 (1).png',
  images: [
    '/WOMENSIMGS/Air Jordan 1 Low-1 (2).png',
    '/WOMENSIMGS/Air Jordan 1 Low-1 (3).png',
    '/WOMENSIMGS/Air Jordan 1 Low-1 (4).png',
    '/WOMENSIMGS/Air Jordan 1 Low-1 (5).png',
    '/WOMENSIMGS/Air Jordan 1 Low-1 (6).png',
    '/WOMENSIMGS/Air Jordan 1 Low-1 (7).png',
    '/WOMENSIMGS/Air Jordan 1 Low-1 (8).png',
  ],
  description:'Air Jordan 1',
  Text:'Immer legendär, immer frisch. Der Air Jordan 1 Low vermittelt ein Stück der Geschichte und Tradition Jordans und sorgt den ganzen Tag über für bequemen Tragekomfort. Wähle deine Farben und entscheide dich für das legendäre Profil mit einer hochwertigen Materialmischung und gekapseltem Air in der Ferse.',
  sizes:['40', '41', '42', '42,5', '43', '44', '44,5', '45', '45,5', '46', '47,5', '48,5'],
  stock: 50,
  type: ['women', 'summer'],
 },
 {
  id: 19,
  title: 'Air Jordan 1 Low',
  price: '$180.00',
  mainImage: '/WOMENSIMGS/Air Jordan 1 Low-2 (1).png',
  images: [
    '/WOMENSIMGS/Air Jordan 1 Low-2 (2).png',
    '/WOMENSIMGS/Air Jordan 1 Low-2 (3).png',
    '/WOMENSIMGS/Air Jordan 1 Low-2 (4).png',
    '/WOMENSIMGS/Air Jordan 1 Low-2 (5).png',
    '/WOMENSIMGS/Air Jordan 1 Low-2 (6).png',
    '/WOMENSIMGS/Air Jordan 1 Low-2 (7).png',
    '/WOMENSIMGS/Air Jordan 1 Low-2 (8).png',
  ],
  description:'Air Jordan 1',
  Text:'Immer legendär, immer frisch. Der Air Jordan 1 Low vermittelt ein Stück der Geschichte und Tradition Jordans und sorgt den ganzen Tag über für bequemen Tragekomfort. Wähle deine Farben und entscheide dich für das legendäre Profil mit einer hochwertigen Materialmischung und gekapseltem Air in der Ferse.',
  sizes:['40', '41', '42', '42,5', '43', '44', '44,5', '45', '45,5', '46', '47,5', '48,5'],
  stock: 50,
  type: ['women', 'summer'],
 },
 {
  id: 20,
  title: 'Air Jordan 1 Low',
  price: '$170.00',
  mainImage: '/WOMENSIMGS/Air Jordan 1 Low-3  (1).png',
  images: [
    '/WOMENSIMGS/Air Jordan 1 Low-3  (2).png',
    '/WOMENSIMGS/Air Jordan 1 Low-3  (3).png',
    '/WOMENSIMGS/Air Jordan 1 Low-3  (4).png',
    '/WOMENSIMGS/Air Jordan 1 Low-3  (5).png',
    '/WOMENSIMGS/Air Jordan 1 Low-3  (6).png',
    '/WOMENSIMGS/Air Jordan 1 Low-3  (7).png',
  ],
  description:'Air Jordan 1',
  Text:'Immer legendär, immer frisch. Der Air Jordan 1 Low vermittelt ein Stück der Geschichte und Tradition Jordans und sorgt den ganzen Tag über für bequemen Tragekomfort. Wähle deine Farben und entscheide dich für das legendäre Profil mit einer hochwertigen Materialmischung und gekapseltem Air in der Ferse.',
  sizes:['40', '41', '42', '42,5', '43', '44', '44,5', '45', '45,5', '46', '47,5', '48,5'],
  stock: 50,
  type: ['women', 'summer'],
 },
 {
  id: 21,
  title: 'Jumpman MVP',
  price: '$160.00',
  mainImage: '/WOMENSIMGS/Jumpman MVP-1 (1).png',
  images: [
    '/WOMENSIMGS/Jumpman MVP-1 (2).png',
    '/WOMENSIMGS/Jumpman MVP-1 (3).png',
    '/WOMENSIMGS/Jumpman MVP-1 (4).png',
    '/WOMENSIMGS/Jumpman MVP-1 (5).png',
    '/WOMENSIMGS/Jumpman MVP-1 (6).png',
    '/WOMENSIMGS/Jumpman MVP-1 (7).png',
    '/WOMENSIMGS/Jumpman MVP-1 (8).png',
  ],
  description:'Air Jordan 1',
  Text:'Immer legendär, immer frisch. Der Air Jordan 1 Low vermittelt ein Stück der Geschichte und Tradition Jordans und sorgt den ganzen Tag über für bequemen Tragekomfort. Wähle deine Farben und entscheide dich für das legendäre Profil mit einer hochwertigen Materialmischung und gekapseltem Air in der Ferse.',
  sizes:['40', '41', '42', '42,5', '43', '44', '44,5', '45', '45,5', '46', '47,5', '48,5'],
  stock: 50,
  type: ['women', 'winter'],
 }
]